### ISSUE TITLE
new release needed for python 3.12 compatibility at build time

### ISSUE THREAD

**Issue by kanavin** [pyca/bcrypt#666]
Now that python 3.12.0 is out, there should be a new release of bcrypt as well, as latest tagged version fails to build with it.

**Comment by alex** [comment]
We build abi3 wheels, which should work fine with Python 3.12.

**Comment by kanavin** [comment]
Where can those be found?

We (yocto project) build from source obtained via https://pypi.org/project/bcrypt/, and that only has the latest tagged version.

**Comment by alex** [comment]
The wheels are the binary artifacts there. For building from source, https://github.com/pyca/bcrypt/blob/main/.github/workflows/wheel-builder.yml#L52-L58 is what we do to build abi3 wheels. Because they're forwards compatible as new python versions are released, a 3.11 (or 3.7) abi3 wheel works fine on Python 3.12.

**Comment by alex** [comment]
The wheels are the binary artifacts there. For building from source, https://github.com/pyca/bcrypt/blob/main/.github/workflows/wheel-builder.yml#L52-L58 is what we do to build abi3 wheels. Because they're forwards compatible as new python versions are released, a 3.11 (or 3.7) abi3 wheel works fine on Python 3.12.

**Comment by kanavin** [comment]
So do I take it that:
- no tagged release is planned
- in order to build from source against python 3.12, we need to take the latest git commit?

For reference, here's the error with 4.0.1:

```
| error[E0425]: cannot find function, tuple struct or tuple variant `PyUnicode_READY` in module `ffi`
|    --> /usr/src/debug/python3-bcrypt/4.0.1-r0/cargo_home/bitbake/pyo3-0.15.2/src/types/string.rs:232:30
|     |
| 232 |             let ready = ffi::PyUnicode_READY(ptr);
|     |                              ^^^^^^^^^^^^^^^ help: a function with a similar name exists: `PyUnicode_IS_READY`
|     |
|    ::: /usr/src/debug/python3-bcrypt/4.0.1-r0/cargo_home/bitbake/pyo3-0.15.2/src/ffi/cpython/unicodeobject.rs:224:1
|     |
| 224 | pub unsafe fn PyUnicode_IS_READY(op: *mut PyObject) -> c_uint {
|     | ------------------------------------------------------------- similarly named function `PyUnicode_IS_READY` defined here
| 
| For more information about this error, try `rustc --explain E0425`.
| error: could not compile `pyo3` (lib) due to previous error
| 
```

**Comment by kanavin** [comment]
Note that this is about being able to build with 3.12, not whether any previous binary artifacts work with 3.12.

**Comment by alex** [comment]
I don't think we have any objection to doing a new release, I was rather trying to explain what could be done without a release (and why there hadn't been any motivation to do one thus far).

**Comment by kanavin** [comment]
Right, I hope it can be done soon-ish :)

**Comment by dragonshinju7** [comment]
Is it compatible with pycbc library??
